name: My Target Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: ${{ inputs.name }}
        run: echo "My name is ${{ inputs.name }}"
