name: My Target Workflow

on:
  repository_dispatch:
    types: [trigger-workflow]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: ${{ github.event.client_payload.id }}
        run: echo "ID is ${{ github.event.client_payload.id }}"